version: "3.9"

services:
  tomcat-container:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql-container:
        condition: service_healthy

  mysql-container:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - type: bind
        source: src/main/resources/mysql
        target: /docker-entrypoint-initdb.d/
      - mysql-volume:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES\""
      interval: 2s
      timeout: 30s
      retries: 30

volumes:
  mysql-volume: